language: python
python: 2.7
services:
  - couchdb
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py33-json
  - TOX_ENV=py34-json
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
